version: "3.8"

x-airflow-common:
  &airflow-common
  image: apache/airflow:2.9.1-python3.9
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__FERNET_KEY: ""
    AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
    AIRFLOW__CORE__PLUGINS_FOLDER: /opt/airflow/plugins
    AIRFLOW__CORE__PIP_ADDITIONAL_REQUIREMENTS: /requirements.txt
    AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow  # Aqui está a URL do banco de dados
  volumes:
    - ./dags:/opt/airflow/dags
    - ./plugins:/opt/airflow/plugins
    - ./logs:/opt/airflow/logs
    - ../project_evolution_part1:/opt/airflow/project_evolution_part1
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    environment:
      <<: *airflow-common-env

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    environment:
      <<: *airflow-common-env

  airflow-init:
    <<: *airflow-common
    volumes:
      - ./requirements.txt:/requirements.txt
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./logs:/opt/airflow/logs
      - ../project_evolution_part1:/opt/airflow/project_evolution_part1
    command: >
      bash -c "pip install -r /requirements.txt &&
      airflow db upgrade &&
      airflow users create --username admin --password admin --firstname Rodrigo --lastname Moraes --role Admin --email admin@example.com"

volumes:
  postgres-db-volume: